### ISSUE TITLE
rfm_edf_ecomanager fails to build with Arduino 1.6.7

### ISSUE THREAD

**Issue by peterg10** [JackKelly/rfm_edf_ecomanager#56]
I pulled the current master branch (and the `nanode_rf_utils` library) and attempted to build with Arduino 1.6.7 on Mac OSX 10.11.2. I get this error:

`sketch/tests/CcArray_test.cpp:8:20: fatal error: iostream: No such file or directory
 #include <iostream>
                    ^
compilation terminated.
exit status 1
Error compiling.`

**Comment by JackKelly** [comment]
Please have a look here from some possibly relevant information: http://forum.arduino.cc/index.php?topic=316263.0

**Comment by peterg10** [comment]
There's a lot of suggestions in that thread. I tried adding the `nanode_rf_utils` library via the Add .zip option in the IDE. Same result:
`sketch/tests/CcArray_test.cpp:8:20: fatal error: iostream: No such file or directory
 #include <iostream>
                    ^
compilation terminated.
Multiple libraries were found for "Rfm12b.h"
 Used: /Users/peter/Documents/Arduino/libraries/nanode_rf_utils-master
 Not used: /Users/peter/Documents/Arduino/libraries/nanode_rf_utils
exit status 1
Error compiling.`

**Comment by JackKelly** [comment]
Try deleting the `tests` directory and then compiling again.  You don't need the tests (unless you want to run tests locally on your PC)

Also, you might not need to compile at all if you don't want to - can you use the (compiled) `hex` file in the `Releases` directory?

**Comment by peterg10** [comment]
You can go ahead and close this. The solution provided by per1234 - "Don't include rfm_edf_ecomanager.cpp from sketch" worked.
